#! /bin/sh

## Simple script to automate common automake-related tasks

echo "== Running aclocal =="
aclocal

echo "== Running libtoolize =="
libtoolize

echo "== Running automake =="
automake --add-missing

echo "== Running autoconf =="
autoconf
