#! /bin/sh

## Simple script to automate common automake-related tasks

echo "== Creating support dir =="
test -d support || mkdir support
 
echo "== Running aclocal =="
aclocal

echo "== Running autoheader =="
autoheader

echo "== Running libtoolize =="
libtoolize

echo "== Running automake =="
automake --add-missing

echo "== Running autoconf =="
autoconf

echo "==> example"
cd example && ./autogen
echo "<== example"
