/* cgicc/config.h.  Generated by configure.  */
/* cgicc/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if debug logging is enabled */
#define DEBUG 0

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* The host system cgicc was configured for */
#define HOST "i686-pc-linux-gnu"

/* Name of package */
#define PACKAGE "cgicc"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bug-cgicc@gnu.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "cgicc"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "cgicc 3.2.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cgicc"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.2.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Version number of package */
#define VERSION "3.2.1"
