<!-- $Id: footer.inc,v 1.6 1998/10/05 22:35:20 sbooth Exp $ -->

<P class="legal">
<A HREF="http://www.lmi.net"><IMG SRC="images/lmi-logo.gif" 
	HEIGHT="92" WIDTH="140" ALT="LMI.net" ALIGN="RIGHT" BORDER="0"></A>
<A HREF="http://www.lmi.net/~sbooth/">Stephen F. Booth</A> (
<A HREF="mailto:sbooth@lmi.net?Subject=Cgicc"><TT>sbooth@lmi.net</TT></A>)<BR>
&copy; Copyright 1996,1997,1998. All Rights Reserved.<BR CLEAR="ALL">
</P>
