<!-- $Id: footer.inc,v 1.10 1999/01/06 00:27:50 sbooth Exp $ -->

<P class="legal">
<A HREF="http://www.lmi.net"><IMG SRC="lmi-logo.gif" 
	HEIGHT="92" WIDTH="140" ALT="LMI.net" ALIGN="RIGHT" BORDER="0"></A>
<A HREF="http://www.lmi.net/~sbooth/">Stephen F. Booth</A> (
<A HREF="mailto:sbooth@saaba.lmi.net?Subject=Cgicc">
<TT>sbooth@saaba.lmi.net</TT></A>)<BR>
&copy; Copyright Stephen F. Booth, 1996, 1997, 1998, 1999. All Rights Reserved.
<BR CLEAR="ALL">
</P>
