<!-- $Id: footer.inc,v 1.9 1998/12/10 02:08:23 sbooth Exp $ -->

<P class="legal">
<A HREF="http://www.lmi.net"><IMG SRC="lmi-logo.gif" 
	HEIGHT="92" WIDTH="140" ALT="LMI.net" ALIGN="RIGHT" BORDER="0"></A>
<A HREF="http://www.lmi.net/~sbooth/">Stephen F. Booth</A> (
<A HREF="mailto:sbooth@saaba.lmi.net?Subject=Cgicc">
<TT>sbooth@saaba.lmi.net</TT></A>)<BR>
&copy; Copyright Stephen F. Booth, 1996, 1997, 1998. All Rights Reserved.
<BR CLEAR="ALL">
</P>
