\input texinfo 
@comment -*-texinfo-*-
@comment %**start of header
@setfilename cgicc.info
@settitle GNU cgicc - A C++ library for CGI programming
@comment %**end of header

@setchapternewpage odd
@finalout

@dircategory Libraries
@direntry
* cgicc: (cgicc).                 A C++ library for writing CGI
                                  applications.
@end direntry

@ifinfo
GNU cgicc is a C++ library for developing CGI applications.

Copyright @copyright{} 1996, 1997, 1998, 1999, 2000 Stephen F. Booth

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
     
@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries a copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).
     
@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
sections entitled ``Copying'' and ``GNU General Public License'' are
included exactly as in the original, and provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.
     
Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by the Free Software Foundation.

@end ifinfo
@titlepage
@sp 10
@center @titlefont{GNU cgicc}
@subtitle A C++ class library for developing CGI applications
@author Stephen F. Booth
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1996, 1997, 1998, 1999 Stephen F. Booth

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
     
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
sections entitled ``Copying'' and ``GNU General Public License'' are
included exactly as in the original, and provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.
     
Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by the Free Software Foundation.
@end titlepage

@ifnottex
@node Top, Overview of CGI, (dir), (dir)
@top GNU cgicc

@include version.texi

This document describes the GNU cgicc library, a C++ class library that
facilitates the development of Common Gateway Inteface (CGI)
applications for the World Wide Web (WWW).

This is edition @value{EDITION} of the cgicc documentation, @value{UPDATED}.
@end ifnottex

@menu
* Overview of CGI::             An overview of the Common Gateway Interface
* A tutorial example::          An introductory example to using cgicc
* Library overview::            An overview of cgicc's layout
* CGI classes::                 Classes used to query and manipulate CGI data
* HTTP header classes::         Classes used for returning response information
* HTML generation classes::     Classes used to return a response to the client
* class Cgicc::                 Used to retrieve form information
* class CgiEnvironment::        Used to retrieve CGI information
* class FormEntry::             Represents a single HTML form element
* class FormFile::              Represents a file uploaded via HTTP
* classes for HTTP headers::    Used for generating response information
* classes for HTML output::     Used for generating a client response
* Reporting Bugs::              How to report a bug in cgicc
* Copying::                     Your rights to distribute cgicc
* Concept Index::               Index of concepts introduced in the manual
* Function Index::              Index of member functions
* Data Type Index::             Index of classes





@end menu

@include cgi-overview.texinfo
@include tutorial.texinfo
@include library-overview.texinfo
@include cgi-classes.texinfo
@include http-classes.texinfo
@include html-classes.texinfo
@include class-cgicc.texinfo
@include class-cgienv.texinfo
@include class-formentry.texinfo
@include class-formfile.texinfo
@include classes-http.texinfo
@include classes-html.texinfo
@include reporting-bugs.texinfo
@include gpl.texinfo
@include concept-index.texinfo
@include function-index.texinfo
@include datatype-index.texinfo

@summarycontents
@contents

@bye
