@comment -*-texinfo-*-
@node classes for HTTP headers, classes for HTML output, class FormFile, Top
@unnumbered classes for HTTP headers

@unnumberedsec HTTPCookie

An @code{HTTPCookie} is a name/value pair used to store a piece of
information about the caller using the caller's own machine.  Cookies
are often used as a means to identify users@footnote{The technical
specification for cookies may be found at
@url{http://www.cis.ohio-state.edu/htbin/rfc/rfc2109.html}.}.

@unnumberedsubsec Constructors

@deftypemethod HTTPCookie void HTTPCookie ()
Creates an empty @code{HTTPCookie}.
@end deftypemethod

@deftypemethod HTTPCookie void HTTPCookie (const string& @var{name}, const string& @var{value})
Creates an @code{HTTPCookie} with name @var{name} and value @var{value},
expiring at the end of the current HTTP session.
@end deftypemethod

@deftypemethod HTTPCookie void HTTPCookie (const string& @var{name}, const string& @var{value}, const string& @var{comment}, const string& @var{domain}, unsigned long @var{maxAge}, const string& @var{path}, bool @var{secure})
Creates an @code{HTTPCookie} with name @var{name} and value
@var{value}. @var{comment} is any textual comment to be associated with
the cookie.  @var{domain} is the hostname for which this cookie is
valid.  If @var{domain} is empty, the hostname of the HTTP server which
generates the response will be used.  The cookie will expire in
@var{maxAge} seconds.  @var{path} is the subset of URIs in a domain for
which the cookie is valid.  Generally, @var{path} will be @samp{/}.
@var{secure} indicates if this a secure cookie.
@end deftypemethod

@deftypemethod HTTPCookie void HTTPCookie (const HTTPCookie& @var{cookie})
Copy constructor.  @var{cookie} is the @code{HTTPCookie} to copy.
@end deftypemethod

@unnumberedsubsec Accessor Methods

@deftypemethod HTTPCookie string getName () const
Get the name of this cookie.
@end deftypemethod

@deftypemethod HTTPCookie string getValue () const
Get the value of this cookie.
@end deftypemethod

@deftypemethod HTTPCookie string getComment () const
Get the comment associated with the cookie, if any.
@end deftypemethod

@deftypemethod HTTPCookie string getDomain () const
Get the hostname for which this cookie is valid.  If empty, the cookie
is valid for the hostname generating the HTTP response.
@end deftypemethod

@deftypemethod HTTPCookie {unsigned long} getMaxAge () const
Get the lifetime of the cookie, in seconds.
@end deftypemethod

@deftypemethod HTTPCookie string getPath () const
Get the subset of URIs in a domain for which this cookie is valid.  If
empty, the cookie is valid for all URIs in a domain.
@end deftypemethod

@deftypemethod HTTPCookie bool getSecure () const
Returns @code{true} if this cookie is secure, @code{false} otherwise.
@end deftypemethod

@unnumberedsubsec Mutator Methods

@deftypemethod HTTPCookie void setName (const string& @var{name})
Set the name of this cookie to @var{name}.
@end deftypemethod

@deftypemethod HTTPCookie void setValue (const string& @var{value})
Set the value of this cookie to @var{value}.
@end deftypemethod

@deftypemethod HTTPCookie void setComment (const string& @var{comment})
Set the comment associated with this cookie.
@end deftypemethod

@deftypemethod HTTPCookie void setDomain (const string& @var{domain})
Set the hostname for which this cookie is valid.
@end deftypemethod

@deftypemethod HTTPCookie void setMaxAge (unsigned long @var{maxAge})
Set the lifetime of this cookie, in seconds.
@end deftypemethod

@deftypemethod HTTPCookie void setPath (const string& @var{path})
Set the subset of URIs in a domain for which this cookie is valid to
@var{path}.  
@end deftypemethod

@deftypemethod HTTPCookie void setSecure (bool @var{secure})
Mark this cookie as secure or unsecure.
@end deftypemethod

@unnumberedsec HTTPHeader

@code{HTTPHeader} is the base class for all HTTP headers.  It is rarely
used directly; instead, use one of the provided subclasses.

@deftypemethod HTTPHeader void HTTPHeader (const string& @var{data})
Creates an HTTP header containing data @var{data}.
@end deftypemethod

@deftypemethod HTTPHeader void HTTPHeader (const HTTPHeader& @var{header})
Creates a copy of the @code{HTTPHeader} @var{header}.
@end deftypemethod

@deftypemethod HTTPHeader string getData ()
Get the data contained in this HTTP header.
@end deftypemethod

@unnumberedsec HTTPContentHeader

@code{HTTPContentHeader} is a subclass of @code{HTTPHeader} used to
indicate the type of data returned to the client by the CGI application.

@deftypemethod HTTPContentHeader void HTTPContentHeader (const string& @var{mimeType})
Creates an HTTP header for data of MIME type @var{mimeType}.
@end deftypemethod

@unnumberedsec HTTPRedirectHeader

@code{HTTPRedirectHeader} is a subclass of @code{HTTPHeader} used to
redirect the client to a different URL.

@deftypemethod HTTPRedirectHeader void HTTPRedirectHeader (const string& @var{url})
Creates an HTTP header used to redirect the client to URL @var{url}.
@end deftypemethod

@unnumberedsec HTTPStatusHeader

@code{HTTPStatusHeader} is a subclass of @code{HTTPHeader} used to
return a 3-digit HTTP status code and the associated message.

@deftypemethod HTTPStatusHeader void HTTPStatusHeader (int @var{status}, const string& @var{message})
Creates an HTTP status header.  @var{status} is the 3 digit status code,
for example @samp{404}.  @var{message} is the message associated with
the status code, for example @samp{not found}.
@end deftypemethod

@unnumberedsec HTTPNPHeader

@code{HTTPNPHeader} is a subclass of @code{HTTPHeader} used to indicate
to the HTTP server that it should not parse the data returned by the CGI
application.  Normally, the HTTP server parses the data returned by the
CGI application and fills in certain headers, such as the data size.

@deftypemethod HTTPNPHeader void HTTPNPHeader ()
Creates a non-parsed HTTP header.  This tells the HTTP server that it
should not parse the output of the CGI application.
@end deftypemethod

@unnumberedsec HTTPHTMLHeader

@deftypemethod HTTPHTMLHeader void HTTPHTMLHeader ()
Creates an HTTP header for data of MIME type @samp{text/html}.
@end deftypemethod

@unnumberedsec HTTPPlainHeader

@deftypemethod HTTPPlainHeader void HTTPPlainHeader ()
Creates an HTTP header for data of MIME type @samp{text/plain}.
@end deftypemethod

@unnumberedsec HTTPGIFHeader

@deftypemethod HTTPGIFHeader void HTTPGIFHeader ()
Creates an HTTP header for data of MIME type @samp{image/gif}.
@end deftypemethod

@unnumberedsec HTTPJPEGHeader

@deftypemethod HTTPJPEGHeader void HTTPJPEGHeader ()
Creates an HTTP header for data of MIME type @samp{image/jpeg}.
@end deftypemethod

@unnumberedsec HTTPXBMHeader

@deftypemethod HTTPXBMHeader void HTTPXBMHeader ()
Creates an HTTP header for data of MIME type @samp{image/x-xbitmap}.
@end deftypemethod

@unnumberedsec HTTPAudioHeader

@deftypemethod HTTPAudioHeader void HTTPAudioHeader ()
Creates an HTTP header for data of MIME type @samp{audio/basic}.
@end deftypemethod
