@comment -*-texinfo-*-
@node class FormFile, classes for HTTP headers, class FormEntry, Top
@unnumbered class FormFile

@code{FormFile} is an immutable class representing a file uploaded via
the HTTP file upload mechanism.  If you are going to use file upload in
your CGI application, remember to set the ENCTYPE of the form to
@samp{multipart/form-data}.

@unnumberedsec Constructors

@deftypemethod FormFile void FormFile ()
Default constructor - should not generally be used.
@end deftypemethod

@deftypemethod FormFile void FormFile (const string& @var{name}, const string& @var{filename}, const string& @var{dataType}, const string& @var{data})
Constructor.  @var{name} is the name of the form element, @var{filename}
is the basename of the file on the remote machine, @var{dataType} is the
MIME type of the data, and @var{data} is the actual file contents.
@end deftypemethod

@deftypemethod FormFile void FormFile (const FormFile& @var{file})
Copy constructor.
@var{file} is the @code{FormFile} to copy.
@end deftypemethod

@unnumberedsec Overloaded Operators

@deftypemethod FormFile bool operator== (const FormFile& @var{file}) const
Equality operator.  Returns @code{true} if @var{file} has the same
filename as this @var{FormFile}, @code{false} otherwise.
@end deftypemethod

@deftypemethod FormFile bool operator!= (const FormFile& @var{file}) const
Inequality operator.  Returns @code{false} if @var{file} has the same
filename as this @var{FormFile}, @code{true} otherwise.
@end deftypemethod

@deftypemethod FormFile FormFile& operator= (const FormFile& @var{file})
Assignment operator. Sets the name, filename, dataType, and data of this
@code{FormFile} to those of @var{file}.
@end deftypemethod

@unnumberedsec Accessor Methods

@deftypemethod FormFile void writeToStream (ostream& @var{out})
Writes the data contained in this @code{FormFile} to the stream
@var{out}.
@end deftypemethod

@deftypemethod FormFile string getName () const
Get the name of the form element.
@end deftypemethod

@deftypemethod FormFile string getFilename () const
Get the basename of file on the remote machine.
@end deftypemethod

@deftypemethod FormFile string getDataType () const
Get the MIME type of the file data.
@end deftypemethod

@deftypemethod FormFile string getData () const
Get the file data.
@end deftypemethod

@deftypemethod FormFile string::size_type getDataLength () const
Get the length of the file data, in bytes.
@end deftypemethod

