@comment -*-texinfo-*-
@node Reporting Bugs, Support, classes for HTML output, Top
@unnumbered Reporting Bugs

There is a mailing list for reporting bugs, @email{bug-cgicc@@gnu.org},
to enable the developers to track submitted bug reports.

If you think you have found a bug in cgicc, then you should send as
complete a report as possible to this list. Ideally, you should include
the text you get by running @code{config.guess}, the text you see when
you run @code{configure}, and if you can, a patch made with @code{diff
-u5} which fixes the problem. 

@xref{Support}, for more information on cgicc mailing lists.
