@comment -*-texinfo-*-
@node Support, Copying, Reporting Bugs, Top
@unnumbered Support

The cgicc library has three mailing lists: @email{help-cgicc@@gnu.org},
@email{info-cgicc@@gnu.org}, and @email{bug-cgicc@@gnu.org}:

@itemize @bullet
@item
@email{help-cgicc@@gnu.org} is the main discussion list and is used to
discuss all aspects of cgicc, including development and porting.

@item
@email{info-cgicc@@gnu.org} is a read-only list where announcements
about cgicc are made.

@item
@email{bug-cgicc@@gnu.org} is a special list used for reporting bugs.
@xref{Reporting Bugs}, for details on submitting a bug report.
@end itemize

To subscribe to any of these lists, send a message to the appropriate
@email{-request} list with the word @kbd{subscribe} in the subject line.
For example, to subscribe to @email{info-cgicc@@gnu.org}, send a message
to @email{info-cgicc-request@@gnu.org} with a subject of
@kbd{subscribe}.

Web interfaces to the lists are available at
@url{http://mail.gnu.org/mailman/listinfo/help-cgicc},
@url{http://mail.gnu.org/mailman/listinfo/info-cgicc}, or
@url{http://mail.gnu.org/mailman/listinfo/bug-cgicc}.
